version: "3.7"
services:
  mysql_db_container:
    network_mode: host
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci --datadir=/data/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isensedb
      MYSQL_USER: isenseuser
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - data.vol:/data
#    logging:
#      driver: journald
#      options:
#        tag: scorer-hokutsu_db
    restart: always
    tty: true

  adminer_container:
    network_mode: host
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080
#    logging:
#      driver: journald
#      options:
#        tag: scorer-hokutsu_adminer
    restart: always
    tty: true

volumes:
  #  mysql_fti_volume:
  data.vol:
    external: true
